@startuml 02-login-autentikasi
title Alur Login dan Autentikasi - DashboardGuru

start

:Admin login ke sistem\ndan mendaftar serial;

:Input kredensial:\n- Username/Email\n- Password;

if (Sistem menghasilkan\nsesi untuk user serial?) then (Tidak)
  :Sistem menampilkan daftar\nerror yang terjadi di\nsistem serial;
  
  if (Admin Mengirimkan\nulang?) then (Ya)
    :Kembali ke input kredensial;
    stop
  else (Tidak)
    stop
  endif
  
else (Ya)
  :Kontak dan Data;
  
  :Sistem menampilkan daftar serial\nyang berhasilan\naktif dan berhubungan;
  
  :Sistem menampilkan daftar sistem\nperpanjangan\ndata berlangsanan;
  
  :Admin mengirimkan;
  
  stop
endif

@enduml
